### ISSUE TITLE
author elb allows login on https but not http.

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [shinesolutions/aem-aws-stack-builder#25]
author elb allows login on https but not http.

not sure if this is intended or not, given the stack does allow access via http.

if it is intended - it would be useful to have a redirect to https in the apache configuration.

**Comment by cliffano** [comment]
Fixed since v2.0.0 .
Both author-dispatcher and author ELBs are listening on both http (port 80) and https (port 443).
Security groups also allow the components to be accessed on both.

The redirection to https in apache will be up to the users to decide.
User will configure it in their own dispatcher artifact's httpd.conf .
